#!/usr/bin/env python3
"""Mechanical checks for a mirage project.

The contract is docs/validator.md in the mirage repository: the files read,
the formats accepted, the diagnostic codes and the commands. Standard library
only, Python 3.9 or newer.
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import re
import stat
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional, Sequence, Tuple, Union
from urllib.parse import unquote

MIRAGE_VERSION = "0.1.0"

GROUPS: Dict[str, Tuple[str, ...]] = {
    "project": ("project-json",),
    "docs": ("doc-missing", "doc-marker", "doc-section", "doc-placeholder", "claude-import", "adr-duplicate"),
    "index": ("index-stale",),
    "register": (
        "register-parse", "register-duplicate", "register-field", "register-status",
        "register-recommendation", "register-answer", "register-covers",
        "inputs-parse", "inputs-duplicate", "inputs-field", "inputs-status", "inputs-kind",
        "inputs-needed-for", "inputs-how", "inputs-location", "inputs-reason",
    ),
    "prd": ("prd-id", "prd-duplicate", "prd-scope", "prd-release", "prd-area"),
    "refs": ("ref-missing",),
    "coverage": ("coverage-req", "coverage-area"),
    "backlog": (
        "backlog-filename", "backlog-id", "backlog-frontmatter", "backlog-field",
        "backlog-hierarchy", "backlog-ref", "backlog-cycle", "backlog-ready", "backlog-blocked",
        "backlog-done", "backlog-section", "backlog-estimate", "backlog-label", "backlog-kind",
        "backlog-due", "backlog-replace",
    ),
    "sources": ("sources-missing", "sources-hash", "sources-unlisted"),
    "links": ("link-broken",),
    "secrets": ("secret",),
}
# Codes that a command reports and no `check` group owns.
COMMAND_CODES: Dict[str, str] = {"prd-empty": "docs-ready", "audit-missing": "docs-ready"}
CODES: Dict[str, str] = {
    **{code: group for group, codes in GROUPS.items() for code in codes},
    **COMMAND_CODES,
}
DOCS_READY_GROUPS = ("project", "docs", "register", "prd", "refs", "links", "sources", "secrets")
AUDIT_LOG = "docs/audit-log.md"
# An entry heading written by mirage-audit, such as `## 2026-10-08 Documents and backlog`.
AUDIT_ENTRY = re.compile(r"## \d{4}-\d{2}-\d{2} Documents\b")

PROJECT_FILE = ".mirage/project.json"
PROJECT_CATALOG = ".mirage/catalog.json"
TRACKERS_DIR = ".mirage/trackers"
QUESTIONS_FILE = "docs/questions.md"
INPUTS_FILE = "docs/inputs.md"
PRD_FILE = "docs/prd.md"
ADR_DIR = "docs/adr"
SOURCES_DIR = "docs/sources"
BACKLOG_DIR = "backlog"
DOCS_INDEX = "docs/README.md"
BACKLOG_INDEX = "backlog/README.md"
GENERATED_NOTE = "Generated by `check.py index`. Edit the source files and run it again; do not edit this file."

SLUG = re.compile(r"[a-z0-9][a-z0-9-]*")
DATE = re.compile(r"(?<!\d)\d{4}-\d{2}-\d{2}(?!\d)")
REQ_ID = re.compile(r"REQ-([A-Z][A-Z0-9]{1,7})-\d{3}")
DOC_MARKER = re.compile(r"<!--\s*mirage:doc\s+(\S+)\s*-->")
SECTION_MARKER = re.compile(r"<!--\s*mirage:section\s+(\S+)\s*-->")
TODO_MARKER = "<!-- mirage:todo"
FENCE_OPEN = re.compile(r"^ {0,3}(`{3,}|~{3,})")
FENCE_CLOSE = re.compile(r"^ {0,3}(`{3,}|~{3,})\s*$")
CHECKLIST = re.compile(r"^\s*- \[[ x]\]")
ADR_FILE = re.compile(r"(\d{4})-.+\.md")
SUMS_LINE = re.compile(r"([0-9a-fA-F]{64})  (.+)")

QUESTION_STATUSES = ("open", "answered", "delegated")
INPUT_STATUSES = ("missing", "provided", "not-needed")
INPUT_KINDS = ("information", "asset", "account", "access", "tool")
PRD_SCOPES = ("MUST", "SHOULD", "MAY", "OUT")

LEVELS = ("milestone", "epic", "story", "task")
LEVEL_RANK = {level: rank for rank, level in enumerate(LEVELS)}
LEVEL_PLURALS = {"milestone": "Milestones", "epic": "Epics", "story": "Stories", "task": "Tasks"}
WORK_LEVELS = ("story", "task")
ID_LEVELS = (
    ("task", re.compile(r"M\d+-E\d{2}-S\d{2}-T\d{2}")),
    ("story", re.compile(r"M\d+-E\d{2}-S\d{2}")),
    ("milestone", re.compile(r"M\d+")),
    ("epic", re.compile(r"E\d{2}")),
)
ITEM_FILENAME = re.compile(r"(M\d+(?:-E\d{2}-S\d{2}(?:-T\d{2})?)?|E\d{2})-([a-z0-9][a-z0-9-]*)\.md")
STATUSES = ("draft", "blocked", "ready", "in-progress", "in-review", "done", "cancelled")
STORY_KINDS = ("feature", "spike", "bug", "chore", "docs")
PRIORITIES = ("urgent", "high", "medium", "low")
STORY_SCOPES = ("must", "should", "may")
ESTIMATES = ("1", "2", "3", "5", "8")
BODY_REQUIRED = ("context", "acceptance", "verification", "out-of-scope")
BODY_OPTIONAL = ("technical",)
BODY_STATUSES = ("ready", "in-progress", "in-review", "done")
MIRAGE_COMMENT = re.compile(r"<!--\s*mirage:(?:(?!-->).)*-->")

KEY_LEVELS: Dict[str, Tuple[str, ...]] = {
    "id": LEVELS, "title": LEVELS, "status": LEVELS,
    "kind": ("story",), "priority": ("story",), "scope": ("story",), "release": ("story",),
    "req": ("story",), "questions": WORK_LEVELS, "inputs": WORK_LEVELS, "blocked_by": WORK_LEVELS,
    "labels": LEVELS, "lane": WORK_LEVELS, "estimate": WORK_LEVELS,
    "evidence": LEVELS, "blocked_reason": LEVELS, "replaces": LEVELS, "replaced_by": LEVELS,
    "due": LEVELS, "due_evidence": LEVELS,
}
LIST_KEYS = ("req", "questions", "inputs", "blocked_by", "labels")
REQUIRED_FIELDS: Dict[str, Tuple[str, ...]] = {
    "title": LEVELS, "status": LEVELS, "priority": ("story",), "scope": ("story",), "release": ("story",),
}
FIELD_DOMAINS: Dict[str, Tuple[str, ...]] = {
    "status": STATUSES, "priority": PRIORITIES, "scope": STORY_SCOPES,
}

SECRET_PATTERNS = (
    ("private key header", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("AWS access key", re.compile(r"AKIA[0-9A-Z]{16}")),
    ("Stripe live key", re.compile(r"sk_live_[0-9A-Za-z]{10,}")),
    ("GitHub token", re.compile(r"gh[pousr]_[A-Za-z0-9]{36,}")),
    ("Slack token", re.compile(r"xox[abprs]-[A-Za-z0-9-]{10,}")),
)


class UsageError(Exception):
    """A refused command, or an input that cannot be read. Exit code 2."""


@dataclass(frozen=True)
class Diagnostic:
    path: str
    line: Optional[int]
    code: str
    message: str

    def __post_init__(self) -> None:
        if self.code not in CODES:
            raise ValueError(f"unknown diagnostic code {self.code}")

    def sort_key(self) -> tuple:
        return (self.path, self.line or 0, self.code, self.message)

    def render(self) -> str:
        where = f"{self.path}:{self.line}" if self.line else self.path
        return f"{where}: {self.code}: {self.message}"

    def as_json(self) -> dict:
        return {"path": self.path, "line": self.line, "code": self.code, "message": self.message}


@dataclass(frozen=True)
class Section:
    key: str
    title: str


@dataclass(frozen=True)
class Area:
    key: str
    ask: str


@dataclass(frozen=True)
class TypicalInput:
    key: str
    title: str
    kind: str


When = Tuple[str, object]


@dataclass(frozen=True)
class DocKind:
    id: str
    title: str
    path: str
    when: When
    check: str
    sections: Tuple[Section, ...]
    areas: Tuple[Area, ...]
    inputs: Tuple[TypicalInput, ...]
    # Older names for the same file, accepted when the project already has one.
    alt_paths: Tuple[str, ...] = ()


@dataclass(frozen=True)
class Catalog:
    component_kinds: Tuple[str, ...]
    flags: Tuple[str, ...]
    lists: Tuple[str, ...]
    docs: Tuple[DocKind, ...]


@dataclass(frozen=True)
class Component:
    id: str
    kind: str


@dataclass
class Facets:
    """The parsed .mirage/project.json. Invalid entries are dropped after being reported."""

    name: str
    components: List[Component]
    flags: Dict[str, bool]
    lists: Dict[str, List[str]]
    releases: List[str]
    areas: List[str]
    require_confirmed_delegation: bool


@dataclass(frozen=True)
class PlannedDoc:
    key: str
    kind: DocKind
    path: str
    reason: str

    @property
    def area_keys(self) -> List[str]:
        return [f"{self.key}/{area.key}" for area in self.kind.areas]


@dataclass(frozen=True)
class Field:
    value: str
    line: int


@dataclass
class RegisterEntry:
    id: str
    title: str
    line: int
    fields: Dict[str, Field]

    def value(self, key: str) -> str:
        entry = self.fields.get(key)
        return entry.value if entry else ""

    def line_of(self, key: str) -> int:
        entry = self.fields.get(key)
        return entry.line if entry else self.line

    def entries(self, key: str) -> List[str]:
        return [part.strip() for part in self.value(key).split(",") if part.strip()]

    @property
    def status(self) -> str:
        return self.value("Status")


class Question(RegisterEntry):
    @property
    def covers(self) -> List[str]:
        return self.entries("Covers")

    @property
    def blocks(self) -> List[str]:
        return self.entries("Blocks")


class Input(RegisterEntry):
    @property
    def needed_for(self) -> List[str]:
        return self.entries("Needed for")

    @property
    def satisfied(self) -> bool:
        return self.status in ("provided", "not-needed")


@dataclass(frozen=True)
class Requirement:
    id: str
    text: str
    scope: str
    release: str
    line: int

    @property
    def area(self) -> Optional[str]:
        match = REQ_ID.fullmatch(self.id)
        return match.group(1) if match else None


FmValue = Union[str, Tuple[str, ...]]


@dataclass(frozen=True)
class FmField:
    value: FmValue
    line: int


@dataclass
class Item:
    id: str
    path: str
    fields: Dict[str, FmField]
    body: List[str]
    body_line: int
    frontmatter_ok: bool

    @property
    def level(self) -> str:
        return level_of(self.id) or ""

    def scalar(self, key: str) -> str:
        entry = self.fields.get(key)
        return entry.value if entry and isinstance(entry.value, str) else ""

    def listed(self, key: str) -> Tuple[str, ...]:
        entry = self.fields.get(key)
        return entry.value if entry and isinstance(entry.value, tuple) else ()

    def line(self, key: str) -> Optional[int]:
        entry = self.fields.get(key)
        return entry.line if entry else None

    @property
    def title(self) -> str:
        return self.scalar("title")

    @property
    def status(self) -> str:
        return self.scalar("status")

    @property
    def kind(self) -> str:
        return self.scalar("kind") or "feature"

    @property
    def areas(self) -> List[str]:
        found: List[str] = []
        for label in self.listed("labels"):
            if label.startswith("area:") and label[5:] not in found:
                found.append(label[5:])
        return found

    @property
    def lane(self) -> Optional[str]:
        if self.scalar("lane"):
            return self.scalar("lane")
        return self.areas[0] if len(self.areas) == 1 else None

    @property
    def estimate(self) -> Optional[int]:
        value = self.scalar("estimate")
        return int(value) if value in ESTIMATES else None

    @property
    def milestone(self) -> Optional[str]:
        return self.id.split("-")[0] if self.level in WORK_LEVELS else None

    @property
    def epic(self) -> Optional[str]:
        return self.id.split("-")[1] if self.level in WORK_LEVELS else None

    @property
    def parent(self) -> Optional[str]:
        if self.level == "story":
            return self.epic
        if self.level == "task":
            return self.id.rsplit("-", 1)[0]
        return None

    @property
    def has_checklist(self) -> bool:
        return any(CHECKLIST.match(line) for _, line in unfenced(self.body))


@dataclass
class Project:
    root: Path
    catalog: Catalog
    facets: Facets
    plan: List[PlannedDoc]
    questions: List[Question]
    inputs: List[Input]
    requirements: List[Requirement]
    prd_areas: Dict[str, int]
    items: Dict[str, Item]
    parse_diagnostics: List[Diagnostic]
    question_by_id: Dict[str, Question] = field(init=False)
    input_by_id: Dict[str, Input] = field(init=False)
    requirement_ids: Dict[str, Requirement] = field(init=False)

    def __post_init__(self) -> None:
        self.question_by_id = first_by_id(self.questions)
        self.input_by_id = first_by_id(self.inputs)
        self.requirement_ids = {}
        for req in self.requirements:
            if REQ_ID.fullmatch(req.id):
                self.requirement_ids.setdefault(req.id, req)

    @property
    def unique_questions(self) -> List[Question]:
        return [self.question_by_id[key] for key in sorted(self.question_by_id)]

    @property
    def unique_inputs(self) -> List[Input]:
        return [self.input_by_id[key] for key in sorted(self.input_by_id)]

    def items_at(self, *levels: str) -> List[Item]:
        return sorted(
            (item for item in self.items.values() if item.level in levels),
            key=lambda item: (LEVEL_RANK[item.level], natural_key(item.id)),
        )


def first_by_id(entries: Sequence[RegisterEntry]) -> dict:
    found: dict = {}
    for entry in entries:
        found.setdefault(entry.id, entry)
    return found


def level_of(item_id: str) -> Optional[str]:
    for level, pattern in ID_LEVELS:
        if pattern.fullmatch(item_id):
            return level
    return None


def natural_key(item_id: str) -> tuple:
    return (item_id[:1], tuple(int(n) for n in re.findall(r"\d+", item_id)), item_id)


def read_text(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except (FileNotFoundError, IsADirectoryError, NotADirectoryError):
        return None


def unfenced(lines: Sequence[str], first_line: int = 1) -> List[Tuple[int, str]]:
    """Numbered lines outside fenced code blocks, fence lines excluded."""
    kept: List[Tuple[int, str]] = []
    fence: Optional[str] = None
    for number, line in enumerate(lines, first_line):
        if fence is None:
            opening = FENCE_OPEN.match(line)
            if opening:
                fence = opening.group(1)
            else:
                kept.append((number, line))
            continue
        closing = FENCE_CLOSE.match(line)
        if closing and closing.group(1)[0] == fence[0] and len(closing.group(1)) >= len(fence):
            fence = None
    return kept


def table_cells(line: str) -> Optional[List[str]]:
    text = line.strip()
    if not text.startswith("|"):
        return None
    text = text[1:]
    if text.endswith("|") and not text.endswith("\\|"):
        text = text[:-1]
    return [cell.strip().replace("\\|", "|") for cell in re.split(r"(?<!\\)\|", text)]


def is_separator(cells: Sequence[str]) -> bool:
    return bool(cells) and all(re.fullmatch(r":?-+:?", cell) for cell in cells)


def valid_date(text: str) -> bool:
    try:
        datetime.date.fromisoformat(text)
    except ValueError:
        return False
    return bool(re.fullmatch(r"\d{4}-\d{2}-\d{2}", text))


def frontmatter_end(lines: Sequence[str]) -> int:
    """Index of the first body line, or 0 when the file has no closed frontmatter."""
    if not lines or lines[0].rstrip() != "---":
        return 0
    for index in range(1, len(lines)):
        if lines[index].rstrip() == "---":
            return index + 1
    return 0


def escape_cell(text: str) -> str:
    return text.replace("|", "\\|")


def md_table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> List[str]:
    if not rows:
        return ["None."]
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(escape_cell(cell) for cell in row) + " |" for row in rows]
    return out


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
    handle, temp = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="") as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temp, mode)
        os.replace(temp, path)
    except BaseException:
        try:
            os.unlink(temp)
        except FileNotFoundError:
            pass
        raise


def read_json(path: Path, label: str) -> object:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise UsageError(f"cannot read {label}: {path} does not exist") from None
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise UsageError(f"cannot read {label}: {error}") from None


def catalog_path(root: Path) -> Path:
    vendored = root / PROJECT_CATALOG
    return vendored if vendored.is_file() else Path(__file__).resolve().parent / "catalog.json"


def parse_when(raw: object) -> When:
    if raw == "always":
        return ("always", None)
    if isinstance(raw, dict) and len(raw) == 1:
        ((form, arg),) = raw.items()
        if form == "any":
            subforms = tuple(parse_when(sub) for sub in arg)
            if any(sub[0] not in SINGLE_FORMS for sub in subforms):
                raise ValueError("any takes single-instance forms only")
            return ("any", subforms)
        if form in SINGLE_FORMS or form in PER_FORMS or form == "listed_in":
            return (form, arg)
    raise ValueError(f"unknown when form {raw!r}")


def load_catalog(path: Path) -> Catalog:
    raw = read_json(path, "catalog.json")
    try:
        docs = tuple(
            DocKind(
                id=doc["id"],
                title=doc["title"],
                path=doc["path"],
                when=parse_when(doc["when"]),
                check=doc["check"],
                sections=tuple(Section(s["key"], s["title"]) for s in doc["sections"]),
                areas=tuple(Area(a["key"], a["ask"]) for a in doc["areas"]),
                inputs=tuple(TypicalInput(i["key"], i["title"], i["kind"]) for i in doc["inputs"]),
                alt_paths=tuple(doc.get("alt_paths", ())),
            )
            for doc in raw["docs"]
        )
        return Catalog(tuple(raw["component_kinds"]), tuple(raw["flags"]), tuple(raw["lists"]), docs)
    except (KeyError, TypeError, ValueError, AttributeError) as error:
        raise UsageError(f"cannot read catalog.json: malformed entry: {error}") from None


def is_slug(value: object) -> bool:
    return isinstance(value, str) and bool(SLUG.fullmatch(value))


def load_facets(root: Path, catalog: Catalog) -> Tuple[Facets, List[Diagnostic]]:
    raw = read_json(root / PROJECT_FILE, PROJECT_FILE)
    if not isinstance(raw, dict):
        raise UsageError(f"cannot read {PROJECT_FILE}: the top level must be an object")
    problems: List[str] = []
    allowed = {"mirage_version", "name", "language", "components", "flags", "releases", "areas",
               "require_confirmed_delegation", *catalog.lists}
    problems += [f"unknown key {key}" for key in sorted(set(raw) - allowed)]

    name = raw.get("name")
    if not isinstance(name, str) or not name.strip():
        problems.append("name must be a non-empty string")
        name = ""
    for key in ("mirage_version", "language"):
        if key in raw and not isinstance(raw[key], str):
            problems.append(f"{key} must be a string")

    components: List[Component] = []
    raw_components = raw.get("components")
    if not isinstance(raw_components, list) or not raw_components:
        problems.append("components needs at least one entry")
        raw_components = raw_components if isinstance(raw_components, list) else []
    for index, entry in enumerate(raw_components):
        if not isinstance(entry, dict) or not is_slug(entry.get("id")):
            problems.append(f"components[{index}] needs an id that is a lowercase slug")
        elif entry.get("kind") not in catalog.component_kinds:
            problems.append(f"component {entry['id']} has unknown kind {entry.get('kind')!r}")
        elif any(c.id == entry["id"] for c in components):
            problems.append(f"component id {entry['id']} is used twice")
        else:
            components.append(Component(entry["id"], entry["kind"]))

    flags: Dict[str, bool] = {}
    raw_flags = raw.get("flags", {})
    if not isinstance(raw_flags, dict):
        problems.append("flags must be an object")
        raw_flags = {}
    for key, value in raw_flags.items():
        if key not in catalog.flags:
            problems.append(f"unknown flag {key}")
        elif not isinstance(value, bool):
            problems.append(f"flag {key} must be true or false")
        else:
            flags[key] = value

    lists: Dict[str, List[str]] = {}
    for key in catalog.lists:
        values = raw.get(key, [])
        if not isinstance(values, list):
            problems.append(f"{key} must be a list")
            values = []
        lists[key] = [v for v in values if is_slug(v)]
        problems += [f"{key} entry {v!r} is not a lowercase slug" for v in values if not is_slug(v)]

    releases = raw.get("releases")
    if not isinstance(releases, list) or not releases or not all(
        isinstance(r, str) and r.strip() for r in releases
    ):
        problems.append("releases must be a non-empty list of names")
        releases = [r for r in releases if isinstance(r, str) and r.strip()] if isinstance(releases, list) else []

    areas = raw.get("areas")
    if not isinstance(areas, list) or not areas or not all(is_slug(a) for a in areas):
        problems.append("areas must be a non-empty list of lowercase slugs")
        areas = [a for a in areas if is_slug(a)] if isinstance(areas, list) else []

    confirmed = raw.get("require_confirmed_delegation", False)
    if not isinstance(confirmed, bool):
        problems.append("require_confirmed_delegation must be true or false")
        confirmed = False

    facets = Facets(name, components, flags, lists, releases, areas, confirmed)
    return facets, [Diagnostic(PROJECT_FILE, None, "project-json", p) for p in problems]


def when_always(arg: object, facets: Facets) -> Optional[str]:
    return "always"


def when_component(arg: object, facets: Facets) -> Optional[str]:
    kinds = [kind for kind in arg if any(c.kind == kind for c in facets.components)]
    return "components include " + ", ".join(kinds) if kinds else None


def when_flag(arg: object, facets: Facets) -> Optional[str]:
    return f"flag {arg} is true" if facets.flags.get(arg) else None


def when_nonempty(arg: object, facets: Facets) -> Optional[str]:
    items = sorted(set(facets.lists.get(arg, [])))
    return f"{arg} includes " + ", ".join(items) if items else None


def when_any(arg: object, facets: Facets) -> Optional[str]:
    reasons = [SINGLE_FORMS[form](sub, facets) for form, sub in arg]
    return "; ".join(r for r in reasons if r) or None


def per_item(arg: object, facets: Facets) -> List[Tuple[str, str]]:
    return [(item, f"{arg} includes {item}") for item in sorted(set(facets.lists.get(arg, [])))]


def per_component(arg: object, facets: Facets) -> List[Tuple[str, str]]:
    kinds = sorted({c.kind for c in facets.components if c.kind in arg})
    return [(kind, f"components include {kind}") for kind in kinds]


SINGLE_FORMS: Dict[str, Callable[[object, Facets], Optional[str]]] = {
    "always": when_always,
    "component": when_component,
    "flag": when_flag,
    "nonempty": when_nonempty,
    "any": when_any,
}
PER_FORMS: Dict[str, Tuple[Callable[[object, Facets], List[Tuple[str, str]]], str]] = {
    "per": (per_item, "{item}"),
    "per_component": (per_component, "{kind}"),
}


def planned_path(root: Optional[Path], kind: DocKind) -> str:
    """The kind's path, or an older name for it when only that file exists."""
    if root is not None and not (root / kind.path).exists():
        for alt in kind.alt_paths:
            if (root / alt).exists():
                return alt
    return kind.path


def make_plan(catalog: Catalog, facets: Facets, root: Optional[Path] = None) -> List[PlannedDoc]:
    plan: List[PlannedDoc] = []
    for kind in catalog.docs:
        form, arg = kind.when
        if form in SINGLE_FORMS:
            reason = SINGLE_FORMS[form](arg, facets)
            if reason:
                plan.append(PlannedDoc(kind.id, kind, planned_path(root, kind), reason))
        elif form in PER_FORMS:
            expand, placeholder = PER_FORMS[form]
            for item, reason in expand(arg, facets):
                plan.append(PlannedDoc(f"{kind.id}:{item}", kind, kind.path.replace(placeholder, item), reason))
    return plan


def listed_instances(project: Project) -> List[Tuple[DocKind, str]]:
    """Files that are instances of a `listed_in` kind: every Markdown file under its path prefix."""
    found: List[Tuple[DocKind, str]] = []
    for kind in project.catalog.docs:
        if kind.when[0] != "listed_in":
            continue
        folder = project.root / kind.path.split("{", 1)[0]
        if folder.is_dir():
            for path in sorted(folder.rglob("*.md")):
                if path.is_file():
                    found.append((kind, path.relative_to(project.root).as_posix()))
    return found


@dataclass(frozen=True)
class RegisterSpec:
    path: str
    prefix: str
    code: str
    keys: Tuple[str, ...]
    entry: type


QUESTIONS = RegisterSpec(
    QUESTIONS_FILE, "Q", "register",
    ("Status", "Covers", "Blocks", "Recommendation", "Answer", "Owner", "Questionnaire"), Question,
)
INPUTS = RegisterSpec(
    INPUTS_FILE, "IN", "inputs",
    ("Status", "Kind", "Needed for", "How to get", "Location", "Reason", "Owner"), Input,
)
FIELD_LINE = re.compile(r"- ([A-Za-z][A-Za-z ]*?):(?:[ \t]+(.*))?")


def parse_register(spec: RegisterSpec, text: Optional[str]) -> Tuple[list, List[Diagnostic]]:
    if text is None:
        return [], []
    heading = re.compile(rf"### ({spec.prefix}-\d{{3}}) (\S.*)")
    loose_heading = re.compile(rf"###\s+{spec.prefix}-")
    entries: list = []
    diagnostics: List[Diagnostic] = []
    first_line: Dict[str, int] = {}
    current: Optional[RegisterEntry] = None

    def report(line: int, suffix: str, message: str) -> None:
        diagnostics.append(Diagnostic(spec.path, line, f"{spec.code}-{suffix}", message))

    for number, line in unfenced(text.split("\n")):
        line = line.rstrip()
        if line.startswith("#"):
            match = heading.fullmatch(line)
            if match:
                current = spec.entry(match.group(1), match.group(2).strip(), number, {})
                if current.id in first_line:
                    report(number, "duplicate", f"{current.id} is already defined on line {first_line[current.id]}")
                else:
                    first_line[current.id] = number
                entries.append(current)
            elif loose_heading.match(line):
                report(number, "parse", f"heading must read `### {spec.prefix}-nnn <title>`")
                current = None
            elif re.match(r"#{2,3}\s", line):
                current = None
            continue
        if current is None or not line.startswith("- "):
            continue
        match = FIELD_LINE.fullmatch(line)
        if not match:
            report(number, "parse", f"a field line must read `- Key: value` with Key one of: {', '.join(spec.keys)}")
            continue
        key, value = match.group(1), (match.group(2) or "").strip()
        if key not in spec.keys:
            report(number, "field", f"{current.id} has unknown field {key}; allowed: {', '.join(spec.keys)}")
        elif key in current.fields:
            report(number, "field", f"{current.id} has field {key} twice")
        else:
            current.fields[key] = Field(value, number)
    return entries, diagnostics


def parse_prd(text: Optional[str]) -> Tuple[List[Requirement], Dict[str, int]]:
    if text is None:
        return [], {}
    requirements: List[Requirement] = []
    areas: Dict[str, int] = {}
    rows = unfenced(text.split("\n"))
    in_areas = False
    for index, (number, line) in enumerate(rows):
        marker = SECTION_MARKER.search(line)
        if marker:
            in_areas = marker.group(1) == "areas"
            continue
        cells = table_cells(line)
        if cells is None or is_separator(cells):
            continue
        first = cells[0].strip("`").strip()
        if first.startswith("REQ-"):
            padded = cells + [""] * 4
            requirements.append(Requirement(first, padded[1], padded[2], padded[3], number))
            continue
        next_cells = table_cells(rows[index + 1][1]) if index + 1 < len(rows) else None
        is_header = next_cells is not None and is_separator(next_cells)
        if in_areas and first and not is_header:
            areas.setdefault(first, number)
    return requirements, areas


def parse_quoted(text: str, start: int) -> Tuple[str, int]:
    """Parse a double-quoted string at text[start]; return its value and the index after it."""
    chars: List[str] = []
    index = start + 1
    while index < len(text):
        char = text[index]
        if char == "\\":
            if index + 1 < len(text) and text[index + 1] in "\"\\":
                chars.append(text[index + 1])
                index += 2
                continue
            raise ValueError("only \\\" and \\\\ escapes are allowed")
        if char == '"':
            return "".join(chars), index + 1
        chars.append(char)
        index += 1
    raise ValueError("unterminated quoted string")


def parse_list(text: str) -> Tuple[str, ...]:
    inner = text[1:-1].strip()
    if not inner:
        return ()
    items: List[str] = []
    index = 0
    while True:
        while index < len(inner) and inner[index] == " ":
            index += 1
        if index < len(inner) and inner[index] == '"':
            value, index = parse_quoted(inner, index)
        else:
            end = inner.find(",", index)
            end = len(inner) if end < 0 else end
            value = inner[index:end].strip()
            if not value or any(c in value for c in '"[]'):
                raise ValueError("list items must be bare words or double-quoted strings")
            index = end
        items.append(value)
        while index < len(inner) and inner[index] == " ":
            index += 1
        if index == len(inner):
            return tuple(items)
        if inner[index] != ",":
            raise ValueError("list items must be separated by commas")
        index += 1


def parse_value(raw: str) -> FmValue:
    if raw.startswith('"'):
        value, end = parse_quoted(raw, 0)
        if end != len(raw):
            raise ValueError("text follows the closing quote")
        return value
    if raw.startswith("["):
        if not raw.endswith("]"):
            raise ValueError("an inline list must end with ]")
        return parse_list(raw)
    return raw


FM_LINE = re.compile(r"([a-z_]+):(?:[ \t]+(.*))?")


def parse_frontmatter(lines: Sequence[str]) -> Tuple[Dict[str, FmField], int, List[Tuple[int, str]]]:
    """Parse the strict YAML subset. Returns fields, the body's first index, and (line, error) pairs."""
    if not lines or lines[0].rstrip() != "---":
        return {}, 0, [(1, "the file must start with a --- frontmatter line")]
    body_start = frontmatter_end(lines)
    if body_start == 0:
        return {}, 0, [(1, "the frontmatter has no closing --- line")]
    fields: Dict[str, FmField] = {}
    errors: List[Tuple[int, str]] = []
    for index in range(1, body_start - 1):
        number, line = index + 1, lines[index].rstrip()
        if not line:
            continue
        match = FM_LINE.fullmatch(line)
        if not match:
            errors.append((number, "a frontmatter line must read `key: value`"))
            continue
        key = match.group(1)
        if key in fields:
            errors.append((number, f"key {key} appears twice"))
            continue
        try:
            fields[key] = FmField(parse_value((match.group(2) or "").strip()), number)
        except ValueError as error:
            errors.append((number, f"{key}: {error}"))
    return fields, body_start, errors


def load_backlog(root: Path) -> Tuple[Dict[str, Item], List[Diagnostic]]:
    items: Dict[str, Item] = {}
    diagnostics: List[Diagnostic] = []
    folder = root / BACKLOG_DIR
    files = sorted(p for p in folder.glob("*.md") if p.is_file()) if folder.is_dir() else []
    for path in files:
        if path.name == "README.md":
            continue
        rel = f"{BACKLOG_DIR}/{path.name}"
        match = ITEM_FILENAME.fullmatch(path.name)
        if not match:
            diagnostics.append(Diagnostic(
                rel, None, "backlog-filename",
                "the file name must be <ID>-<slug>.md, such as M1-E02-S03-pay-by-card.md",
            ))
            continue
        item_id = match.group(1)
        if item_id in items:
            diagnostics.append(Diagnostic(rel, None, "backlog-id", f"{item_id} is already used by {items[item_id].path}"))
            continue
        lines = path.read_bytes().decode("utf-8", errors="replace").replace("\r\n", "\n").split("\n")
        fields, body_start, errors = parse_frontmatter(lines)
        diagnostics += [Diagnostic(rel, number, "backlog-frontmatter", message) for number, message in errors]
        items[item_id] = Item(item_id, rel, fields, lines[body_start:], body_start + 1, not errors)
    return items, diagnostics


def load_project(root: Path) -> Project:
    catalog = load_catalog(catalog_path(root))
    facets, diagnostics = load_facets(root, catalog)
    questions, question_diagnostics = parse_register(QUESTIONS, read_text(root / QUESTIONS_FILE))
    inputs, input_diagnostics = parse_register(INPUTS, read_text(root / INPUTS_FILE))
    requirements, prd_areas = parse_prd(read_text(root / PRD_FILE))
    items, backlog_diagnostics = load_backlog(root)
    return Project(
        root, catalog, facets, make_plan(catalog, facets, root), questions, inputs, requirements,
        prd_areas, items, diagnostics + question_diagnostics + input_diagnostics + backlog_diagnostics,
    )


def adr_files(root: Path) -> List[Tuple[str, str]]:
    """(number, relative path) for every docs/adr/NNNN-*.md file, sorted by path."""
    folder = root / ADR_DIR
    if not folder.is_dir():
        return []
    found = [(ADR_FILE.fullmatch(p.name), p) for p in sorted(folder.iterdir()) if p.is_file()]
    return [(m.group(1), p.relative_to(root).as_posix()) for m, p in found if m]


def adr_numbers(root: Path) -> List[str]:
    return sorted({number for number, _ in adr_files(root)})


def is_generated(path: Path) -> bool:
    with open(path, encoding="utf-8", errors="replace") as stream:
        return stream.readline().startswith("<!-- mirage:generated")


def scanned_files(root: Path) -> List[str]:
    """Files the refs, links and secrets groups read. Generated files only repeat IDs from their sources."""
    candidates: List[Path] = []
    docs = root / "docs"
    if docs.is_dir():
        candidates += [p for p in docs.rglob("*.md") if not p.relative_to(root).as_posix().startswith(SOURCES_DIR + "/")]
    backlog = root / BACKLOG_DIR
    if backlog.is_dir():
        candidates += list(backlog.glob("*.md"))
    candidates += [root / name for name in ("AGENTS.md", "GLOSSARY.md", "CONTEXT.md")]
    return sorted(p.relative_to(root).as_posix() for p in candidates if p.is_file() and not is_generated(p))


def scan_lines(root: Path, rel: str) -> List[Tuple[int, str]]:
    """Lines a reference or link scan reads. Backlog frontmatter is left to the backlog group."""
    lines = (read_text(root / rel) or "").split("\n")
    start = frontmatter_end(lines) if rel.startswith(BACKLOG_DIR + "/") else 0
    return unfenced(lines[start:], start + 1)


def check_sections(rel: str, key: str, kind: DocKind, text: str) -> List[Diagnostic]:
    lines = text.split("\n")
    visible = unfenced(lines)
    out: List[Diagnostic] = []
    doc_markers = [(n, m.group(1)) for n, line in visible for m in DOC_MARKER.finditer(line)]
    own = [n for n, found in doc_markers if found == key]
    if not own:
        out.append(Diagnostic(rel, None, "doc-marker", f"missing the doc marker <!-- mirage:doc {key} -->"))
    elif len(own) > 1:
        out.append(Diagnostic(rel, own[1], "doc-marker", f"the doc marker for {key} appears {len(own)} times"))
    for number, found in doc_markers:
        if found != key:
            out.append(Diagnostic(rel, number, "doc-marker", f"the doc marker names {found}; this document is {key}"))

    positions: Dict[str, List[int]] = {}
    for index, (number, line) in enumerate(visible):
        for match in SECTION_MARKER.finditer(line):
            positions.setdefault(match.group(1), []).append(index)
    for section in kind.sections:
        found = positions.get(section.key)
        if not found:
            out.append(Diagnostic(
                rel, None, "doc-section",
                f"missing the section marker <!-- mirage:section {section.key} --> for {section.title}",
            ))
            continue
        if len(found) > 1:
            out.append(Diagnostic(rel, visible[found[1]][0], "doc-section", f"section marker {section.key} appears twice"))
        following = [line for _, line in visible[found[0] + 1:] if line.strip()]
        if not following or not following[0].lstrip().startswith("#"):
            out.append(Diagnostic(
                rel, visible[found[0]][0], "doc-section",
                f"section marker {section.key} must sit directly before its heading",
            ))

    visible_numbers = {n for n, _ in visible}
    for number, line in enumerate(lines, 1):
        braces = number in visible_numbers and "{{" in line
        if braces or TODO_MARKER in line:
            what = "a {{ placeholder" if braces else "a mirage:todo marker"
            out.append(Diagnostic(rel, number, "doc-placeholder", f"the line holds {what}; write the content or cite a question"))
    return out


def check_claude_import(root: Path) -> List[Diagnostic]:
    text = read_text(root / "CLAUDE.md")
    if text is None:
        return [Diagnostic("CLAUDE.md", None, "claude-import", "CLAUDE.md is missing; it must hold the line @AGENTS.md")]
    if "@AGENTS.md" not in text.split("\n"):
        return [Diagnostic("CLAUDE.md", None, "claude-import", "CLAUDE.md has no line that is exactly @AGENTS.md")]
    return []


def rule_docs(project: Project) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    for doc in project.plan:
        if doc.kind.check == "generated":
            continue  # the index group owns generated files, present or not
        text = read_text(project.root / doc.path)
        if text is None:
            out.append(Diagnostic(
                doc.path, None, "doc-missing",
                f"{doc.kind.title} ({doc.key}) is missing; it is planned because {doc.reason}"
                + "".join(f"; {alt} is accepted too" for alt in doc.kind.alt_paths),
            ))
        elif doc.kind.check == "sections":
            out += check_sections(doc.path, doc.key, doc.kind, text)
    for kind, rel in listed_instances(project):
        out += check_sections(rel, kind.id, kind, read_text(project.root / rel) or "")
    if any(doc.kind.id == "agents" for doc in project.plan):
        out += check_claude_import(project.root)
    first: Dict[str, str] = {}
    for number, rel in adr_files(project.root):
        if number in first:
            out.append(Diagnostic(rel, None, "adr-duplicate", f"ADR number {number} is already used by {first[number]}"))
        else:
            first[number] = rel
    return out


def first_difference(actual: str, expected: str) -> int:
    old, new = actual.split("\n"), expected.split("\n")
    for number, (a, b) in enumerate(zip(old, new), 1):
        if a != b:
            return number
    return min(len(old), len(new)) + 1


def rule_index(project: Project) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    for rel, render in GENERATED.items():
        actual = read_text(project.root / rel)
        expected = render(project)
        if actual is None:
            out.append(Diagnostic(rel, None, "index-stale", "the generated file is missing; run index"))
        elif actual != expected:
            out.append(Diagnostic(
                rel, first_difference(actual, expected), "index-stale",
                "the generated file differs from what index writes; run index",
            ))
    return out


def check_question(question: Question, planned_areas: set) -> List[Diagnostic]:
    out: List[Diagnostic] = []

    def report(key: str, code: str, message: str) -> None:
        out.append(Diagnostic(QUESTIONS_FILE, question.line_of(key), code, f"{question.id} {message}"))

    if "Status" not in question.fields:
        report("Status", "register-status", "has no Status; use open, answered or delegated")
    elif question.status not in QUESTION_STATUSES:
        report("Status", "register-status", f"has Status {question.status!r}; use open, answered or delegated")
    if not question.value("Recommendation"):
        report("Recommendation", "register-recommendation", "needs a non-empty Recommendation")
    if question.status in ("answered", "delegated"):
        answer = question.value("Answer")
        if not answer:
            report("Answer", "register-answer", f"is {question.status} but has no Answer")
        elif not any(valid_date(d) for d in DATE.findall(answer)):
            report("Answer", "register-answer", "has an Answer without a date YYYY-MM-DD")
    for key in question.covers:
        if key not in planned_areas:
            report("Covers", "register-covers", f"covers {key}, which is not an area of a planned document")
    return out


def check_input(entry: Input) -> List[Diagnostic]:
    out: List[Diagnostic] = []

    def report(key: str, code: str, message: str) -> None:
        out.append(Diagnostic(INPUTS_FILE, entry.line_of(key), code, f"{entry.id} {message}"))

    if entry.status not in INPUT_STATUSES:
        report("Status", "inputs-status", f"has Status {entry.status!r}; use missing, provided or not-needed")
    if entry.value("Kind") not in INPUT_KINDS:
        report("Kind", "inputs-kind", f"has Kind {entry.value('Kind')!r}; use {', '.join(INPUT_KINDS)}")
    if not entry.needed_for:
        report("Needed for", "inputs-needed-for", "needs a non-empty Needed for")
    if entry.status == "missing" and not entry.value("How to get"):
        report("How to get", "inputs-how", "is missing and needs How to get")
    if entry.status == "provided" and not entry.value("Location"):
        report("Location", "inputs-location", "is provided and needs a Location")
    if entry.status == "not-needed" and not entry.value("Reason"):
        report("Reason", "inputs-reason", "is not-needed and needs a Reason")
    return out


def rule_register(project: Project) -> List[Diagnostic]:
    planned_areas = {key for doc in project.plan for key in doc.area_keys}
    out: List[Diagnostic] = []
    for question in project.questions:
        out += check_question(question, planned_areas)
    for entry in project.inputs:
        out += check_input(entry)
    return out


def rule_prd(project: Project) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    first_line: Dict[str, int] = {}
    releases = project.facets.releases
    for req in project.requirements:
        problems: List[Tuple[str, str]] = []
        if not REQ_ID.fullmatch(req.id):
            problems.append(("prd-id", f"{req.id} must read REQ-<AREA>-<NNN>, such as REQ-PAY-001"))
        elif req.id in first_line:
            problems.append(("prd-duplicate", f"{req.id} is already defined on line {first_line[req.id]}"))
        else:
            first_line[req.id] = req.line
            if req.scope not in PRD_SCOPES:
                problems.append(("prd-scope", f"{req.id} has scope {req.scope!r}; use MUST, SHOULD, MAY or OUT"))
            if not (req.release in releases or (req.scope == "OUT" and req.release == "-")):
                problems.append(("prd-release", f"{req.id} has release {req.release!r}; use one of {', '.join(releases)}"))
            if req.area not in project.prd_areas:
                problems.append(("prd-area", f"{req.id} uses area {req.area}, which the areas section does not declare"))
        out += [Diagnostic(PRD_FILE, req.line, code, message) for code, message in problems]
    return out


def reference_kinds(project: Project) -> List[Tuple[re.Pattern, Callable[[str], bool], str]]:
    adrs = set(adr_numbers(project.root))
    return [
        (re.compile(r"\bREQ-[A-Z][A-Z0-9]{1,7}-\d{3}\b"), lambda ref: ref in project.requirement_ids,
         f"is not a requirement in {PRD_FILE}"),
        (re.compile(r"\bQ-\d{3}\b"), lambda ref: ref in project.question_by_id, f"is not a question in {QUESTIONS_FILE}"),
        (re.compile(r"\bIN-\d{3}\b"), lambda ref: ref in project.input_by_id, f"is not an input in {INPUTS_FILE}"),
        (re.compile(r"\bADR-\d{4}\b"), lambda ref: ref[4:] in adrs, f"has no file {ADR_DIR}/NNNN-*.md"),
        (re.compile(r"\bM\d+-E\d{2}-S\d{2}(?:-T\d{2})?\b"), lambda ref: ref in project.items,
         f"has no file in {BACKLOG_DIR}/"),
    ]


def rule_refs(project: Project) -> List[Diagnostic]:
    kinds = reference_kinds(project)
    out: List[Diagnostic] = []
    for rel in scanned_files(project.root):
        for number, line in scan_lines(project.root, rel):
            reported = set()
            for pattern, exists, missing in kinds:
                for ref in pattern.findall(line):
                    if not exists(ref) and ref not in reported:
                        reported.add(ref)
                        out.append(Diagnostic(rel, number, "ref-missing", f"{ref} {missing}"))
    return out


def check_coverage_req(project: Project) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    rank = {release: index for index, release in enumerate(project.facets.releases)}
    stories = [
        s for s in project.items_at("story")
        if s.status != "cancelled" and s.scalar("release") in rank
    ]
    for req in project.requirement_ids.values():
        if req.scope not in ("MUST", "SHOULD", "MAY") or req.release not in rank:
            continue
        if not any(req.id in s.listed("req") and rank[s.scalar("release")] <= rank[req.release] for s in stories):
            out.append(Diagnostic(
                PRD_FILE, req.line, "coverage-req",
                f"{req.id} is in no live story's req with release {req.release} or earlier",
            ))
    return out


def check_coverage_area(project: Project) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    covered = {key for question in project.questions for key in question.covers}
    for doc in project.plan:
        for area in doc.kind.areas:
            key = f"{doc.key}/{area.key}"
            if key not in covered:
                out.append(Diagnostic(QUESTIONS_FILE, None, "coverage-area", f"no question covers {key}: {area.ask}"))
    return out


def rule_coverage(project: Project) -> List[Diagnostic]:
    return check_coverage_req(project) + check_coverage_area(project)


@dataclass(frozen=True)
class Unmet:
    id: str
    reason: str

    def __str__(self) -> str:
        return f"{self.id} {self.reason}"


def effective(project: Project, item: Item, key: str) -> List[str]:
    """The item's own IDs under key, plus its story's when the item is a task."""
    values = list(item.listed(key))
    story = project.items.get(item.parent or "") if item.level == "task" else None
    if story is not None:
        values += [v for v in story.listed(key) if v not in values]
    return values


def is_spike_work(project: Project, item: Item) -> bool:
    """A spike exists to answer its questions, so they do not hold it or its tasks back."""
    story = project.items.get(item.parent or "") if item.level == "task" else item
    return story is not None and story.level == "story" and story.kind == "spike"


def unmet_prerequisites(project: Project, item: Item) -> List[Unmet]:
    if item.level not in WORK_LEVELS:
        return []
    unmet: List[Unmet] = []
    confirmed = project.facets.require_confirmed_delegation
    for ref in ([] if is_spike_work(project, item) else effective(project, item, "questions")):
        question = project.question_by_id.get(ref)
        if question is None:
            unmet.append(Unmet(ref, "does not exist"))
        elif question.status == "delegated" and confirmed:
            unmet.append(Unmet(ref, "is delegated and awaits confirmation"))
        elif question.status not in ("answered", "delegated"):
            unmet.append(Unmet(ref, f"is {question.status or 'without a status'}"))
    for ref in effective(project, item, "inputs"):
        entry = project.input_by_id.get(ref)
        if entry is None:
            unmet.append(Unmet(ref, "does not exist"))
        elif not entry.satisfied:
            unmet.append(Unmet(ref, f"is {entry.status or 'without a status'}"))
    for ref in effective(project, item, "blocked_by"):
        blocker = project.items.get(ref)
        if blocker is None:
            unmet.append(Unmet(ref, "does not exist"))
        elif blocker.status != "done":
            unmet.append(Unmet(ref, f"is {blocker.status or 'without a status'}"))
    return unmet


def question_blocks(project: Project, question: Question) -> List[str]:
    """What waits on a question: its Blocks field, then every item that lists it and is not the spike answering it."""
    blocks = list(question.blocks)
    for item in sorted(project.items.values(), key=lambda entry: natural_key(entry.id)):
        if question.id in item.listed("questions") and item.id not in blocks and not is_spike_work(project, item):
            blocks.append(item.id)
    return blocks


def descendants(project: Project, item: Item) -> List[Item]:
    if item.level == "story":
        return [t for t in project.items_at("task") if t.parent == item.id]
    if item.level == "epic":
        return [s for s in project.items_at("story") if s.epic == item.id]
    if item.level == "milestone":
        return [s for s in project.items_at("story") if s.milestone == item.id]
    return []


def check_fields(project: Project, item: Item) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    level = item.level

    def report(line: Optional[int], code: str, message: str) -> None:
        out.append(Diagnostic(item.path, line, code, message))

    for key, entry in item.fields.items():
        levels = KEY_LEVELS.get(key)
        if levels is None:
            report(entry.line, "backlog-field", f"unknown key {key}")
        elif level not in levels:
            report(entry.line, "backlog-field", f"{key} is not allowed on a {level}")
        elif key in LIST_KEYS and not isinstance(entry.value, tuple):
            report(entry.line, "backlog-field", f"{key} must be an inline list such as [a, b]")
        elif key not in LIST_KEYS and isinstance(entry.value, tuple):
            report(entry.line, "backlog-field", f"{key} must be a single value, not a list")

    fid = item.fields.get("id")
    if fid is None:
        report(None, "backlog-id", f"the frontmatter has no id; the file name says {item.id}")
    elif fid.value != item.id:
        report(fid.line, "backlog-id", f"id {fid.value} does not match the file name prefix {item.id}")

    for key, levels in REQUIRED_FIELDS.items():
        if level in levels and (key not in item.fields or item.fields[key].value == ""):
            report(item.line(key), "backlog-field", f"{key} is required on a {level}")
    for key, domain in FIELD_DOMAINS.items():
        value = item.scalar(key)
        if value and level in KEY_LEVELS[key] and value not in domain:
            report(item.line(key), "backlog-field", f"{key} {value!r} must be one of {', '.join(domain)}")
    release = item.scalar("release")
    if level == "story" and release and release not in project.facets.releases:
        report(item.line("release"), "backlog-field",
               f"release {release!r} is not one of {', '.join(project.facets.releases)}")
    return out


def check_structure(project: Project, item: Item) -> List[Diagnostic]:
    """Hierarchy, references, replacement, labels, kind, estimate and due date."""
    out: List[Diagnostic] = []
    level = item.level

    def report(line: Optional[int], code: str, message: str) -> None:
        out.append(Diagnostic(item.path, line, code, message))

    if level == "story":
        for needed, what in ((item.milestone, "milestone"), (item.epic, "epic")):
            if needed not in project.items:
                report(None, "backlog-hierarchy", f"story {item.id} needs its {what} file {BACKLOG_DIR}/{needed}-<slug>.md")
    elif level == "task" and item.parent not in project.items:
        report(None, "backlog-hierarchy", f"task {item.id} needs its story file {BACKLOG_DIR}/{item.parent}-<slug>.md")

    targets: Dict[str, Callable[[str], bool]] = {
        "req": lambda ref: ref in project.requirement_ids,
        "questions": lambda ref: ref in project.question_by_id,
        "inputs": lambda ref: ref in project.input_by_id,
        "blocked_by": lambda ref: ref in project.items,
        "replaces": lambda ref: ref in project.items,
        "replaced_by": lambda ref: ref in project.items,
    }
    for key, exists in targets.items():
        if level not in KEY_LEVELS[key]:
            continue
        refs = item.listed(key) if key in LIST_KEYS else tuple(v for v in [item.scalar(key)] if v)
        for ref in refs:
            if not exists(ref):
                report(item.line(key), "backlog-ref", f"{key} names {ref}, which does not exist")
            elif key == "blocked_by":
                blocker = project.items[ref]
                if ref == item.id:
                    report(item.line(key), "backlog-ref", f"{item.id} cannot block itself")
                elif blocker.level not in WORK_LEVELS:
                    report(item.line(key), "backlog-ref", f"blocked_by names {ref}, a {blocker.level}; blockers are stories or tasks")
                elif blocker.status == "cancelled":
                    report(item.line(key), "backlog-ref", f"blocker {ref} is cancelled")

    replaced = project.items.get(item.scalar("replaces"))
    if replaced is not None:
        if replaced.status != "cancelled":
            report(item.line("replaces"), "backlog-replace", f"replaces {replaced.id}, which is {replaced.status}, not cancelled")
        if replaced.scalar("replaced_by") != item.id:
            report(item.line("replaces"), "backlog-replace", f"{replaced.id} must name {item.id} in replaced_by")

    labels_line = item.line("labels")
    for area in item.areas:
        if area not in project.facets.areas:
            report(labels_line, "backlog-label", f"area:{area} is not an area declared in {PROJECT_FILE}")
    if level in WORK_LEVELS:
        lane = item.scalar("lane")
        if not item.areas:
            report(labels_line, "backlog-label", f"a {level} needs at least one area:<area> label")
        if len(item.areas) > 1 and not lane:
            report(labels_line, "backlog-label", f"several areas ({', '.join(item.areas)}); set lane to the owning one")
        if lane and lane not in item.areas:
            report(item.line("lane"), "backlog-label", f"lane {lane} is not one of the item's areas")

    if level == "story":
        if "kind" in item.fields and item.scalar("kind") not in STORY_KINDS:
            report(item.line("kind"), "backlog-kind", f"kind {item.scalar('kind')!r} must be one of {', '.join(STORY_KINDS)}")
        if item.kind == "spike" and not item.listed("questions"):
            report(item.line("kind"), "backlog-kind", "a spike story lists at least one question")

    estimate = item.scalar("estimate")
    if level in WORK_LEVELS and estimate and estimate not in ESTIMATES:
        report(item.line("estimate"), "backlog-estimate", f"estimate {estimate} must be 1, 2, 3, 5 or 8")
    if level == "story" and "estimate" in item.fields:
        both = [t.id for t in descendants(project, item) if "estimate" in t.fields]
        if both:
            report(item.line("estimate"), "backlog-estimate",
                   f"the estimate sits on the story and on its tasks {', '.join(both)}; keep one")

    due = item.scalar("due")
    if "due" in item.fields:
        if not valid_date(due):
            report(item.line("due"), "backlog-due", f"due {due!r} must be a date YYYY-MM-DD")
        if not item.scalar("due_evidence"):
            report(item.line("due"), "backlog-due", "due needs due_evidence")
    return out


def body_section_problems(item: Item) -> List[Tuple[Optional[int], str]]:
    """(line, message) for each defect in a story's or task's body sections, whatever its status."""
    marks: List[Tuple[int, str]] = []  # (index into item.body, section key), in file order
    for number, line in unfenced(item.body, item.body_line):
        marks += [(number - item.body_line, match.group(1)) for match in SECTION_MARKER.finditer(line)]
    problems: List[Tuple[Optional[int], str]] = []
    for key in BODY_REQUIRED + BODY_OPTIONAL:
        at = next((index for index, (_, found) in enumerate(marks) if found == key), None)
        if at is None:
            if key in BODY_REQUIRED:
                problems.append((None, f"section {key} is missing; add the marker <!-- mirage:section {key} --> "
                                       "before its heading"))
            continue
        start = marks[at][0]
        end = marks[at + 1][0] if at + 1 < len(marks) else len(item.body)
        region = item.body[start + 1:end]
        heading = next((index for index, line in enumerate(region) if line.strip()), None)
        if heading is None or not region[heading].lstrip().startswith("#"):
            problems.append((item.body_line + start, f"section marker {key} must sit directly before its heading"))
            continue
        content = region[heading + 1:]
        if key not in BODY_REQUIRED:
            continue
        if not any(line.strip() for line in content):
            problems.append((item.body_line + start, f"section {key} is empty; write at least one line after its heading"))
        elif key == "acceptance" and not any(CHECKLIST.match(line) for _, line in unfenced(content)):
            problems.append((item.body_line + start, "section acceptance has no checklist item"))
    return problems


def check_body(item: Item) -> List[Diagnostic]:
    if item.level not in WORK_LEVELS or item.status not in BODY_STATUSES:
        return []
    return [Diagnostic(item.path, line, "backlog-section", message) for line, message in body_section_problems(item)]


def lacks_requirement(item: Item) -> bool:
    return item.level == "story" and item.kind == "feature" and not item.listed("req")


def check_status(project: Project, item: Item) -> List[Diagnostic]:
    status = item.status
    line = item.line("status")
    out: List[Diagnostic] = []

    def report(code: str, message: str) -> None:
        out.append(Diagnostic(item.path, line, code, message))

    unmet = unmet_prerequisites(project, item)
    if status == "ready":
        if unmet:
            report("backlog-ready", "status is ready but " + ", ".join(str(u) for u in unmet))
        if item.level not in WORK_LEVELS and not item.has_checklist:
            report("backlog-ready", "status is ready but the body has no checklist item")
        if lacks_requirement(item):
            report("backlog-ready", "status is ready but the feature story lists no requirement")
    elif status == "blocked" and not unmet and not item.scalar("blocked_reason"):
        report("backlog-blocked", "status is blocked but every prerequisite is met and blocked_reason is not set")
    elif status == "done":
        if not item.scalar("evidence"):
            report("backlog-done", "status is done but evidence is not set")
        open_items = [d.id for d in descendants(project, item) if d.status not in ("done", "cancelled")]
        if open_items:
            report("backlog-done", f"status is done but not every descendant is done or cancelled: {', '.join(open_items)}")
        if item.level == "story" and item.kind == "spike":
            unanswered = [ref for ref in item.listed("questions")
                          if ref in project.question_by_id and project.question_by_id[ref].status == "open"]
            if unanswered:
                report("backlog-done", f"status is done but the spike's outcome is not recorded: {', '.join(unanswered)} is still open")
    return out


def find_cycle(graph: Dict[str, List[str]]) -> Optional[List[str]]:
    visiting, finished = set(), set()
    for start in sorted(graph, key=natural_key):
        if start in finished:
            continue
        path = [start]
        stack = [iter(graph[start])]
        visiting.add(start)
        while stack:
            nxt = next(stack[-1], None)
            if nxt is None:
                finished.add(path[-1])
                visiting.discard(path.pop())
                stack.pop()
            elif nxt in visiting:
                return path[path.index(nxt):] + [nxt]
            elif nxt not in finished:
                visiting.add(nxt)
                path.append(nxt)
                stack.append(iter(graph[nxt]))
    return None


def check_cycles(project: Project) -> List[Diagnostic]:
    work = {item.id: item for item in project.items_at(*WORK_LEVELS) if item.frontmatter_ok}
    graph = {
        item_id: sorted({b for b in item.listed("blocked_by") if b in work and b != item_id}, key=natural_key)
        for item_id, item in work.items()
    }
    cycle = find_cycle(graph)
    if cycle is None:
        return []
    nodes = cycle[:-1]
    first = min(range(len(nodes)), key=lambda i: natural_key(nodes[i]))
    ordered = nodes[first:] + nodes[:first] + [nodes[first]]
    item = work[ordered[0]]
    return [Diagnostic(item.path, item.line("blocked_by"), "backlog-cycle", "blocked_by cycle: " + " -> ".join(ordered))]


def rule_backlog(project: Project) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    for item in project.items_at(*LEVELS):
        if item.frontmatter_ok:
            out += check_fields(project, item) + check_structure(project, item) + check_status(project, item)
            out += check_body(item)
    return out + check_cycles(project)


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rule_sources(project: Project) -> List[Diagnostic]:
    doc = next((d for d in project.plan if d.kind.check == "sources"), None)
    if doc is None:
        return []
    sums = project.root / doc.path
    text = read_text(sums)
    if text is None:
        return []  # the docs group reports the missing list
    base = sums.parent
    out: List[Diagnostic] = []
    listed = set()
    for number, line in enumerate(text.split("\n"), 1):
        if not line.strip():
            continue
        match = SUMS_LINE.fullmatch(line)
        if not match:
            out.append(Diagnostic(doc.path, number, "sources-hash", "the line must read `<sha256>  <relative path>`"))
            continue
        digest, rel = match.group(1).lower(), match.group(2)
        listed.add(rel)
        target = base / rel
        if target.is_dir():
            out.append(Diagnostic(doc.path, number, "sources-missing", f"{rel} is listed but is a directory, not a file"))
        elif not target.is_file():
            out.append(Diagnostic(doc.path, number, "sources-missing", f"{rel} is listed but does not exist"))
        elif sha256_file(target) != digest:
            out.append(Diagnostic(doc.path, number, "sources-hash", f"{rel} does not match its listed hash"))
    for path in sorted(base.rglob("*")):
        if path.is_file() and path != sums and path.relative_to(base).as_posix() not in listed:
            out.append(Diagnostic(
                path.relative_to(project.root).as_posix(), None, "sources-unlisted",
                f"the file is not listed in {doc.path}",
            ))
    return out


INLINE_CODE = re.compile(r"(`+).+?\1")
INLINE_LINK = re.compile(r"!?\[(?:[^\]\\]|\\.)*\]\(\s*(<[^>]*>|[^)\s]+)(?:\s+(?:\"[^\"]*\"|'[^']*'))?\s*\)")
REFERENCE_DEFINITION = re.compile(r" {0,3}\[[^\]]+\]:\s*(<[^>]*>|\S+).*")
URL_SCHEME = re.compile(r"[A-Za-z][A-Za-z0-9+.-]*:")


def link_exists(root: Path, rel: str, target: str) -> bool:
    target = target.strip("<>")
    if not target or target.startswith("#") or URL_SCHEME.match(target):
        return True
    target = unquote(target.split("#", 1)[0].split("?", 1)[0])
    base = root if target.startswith("/") else (root / rel).parent
    return (base / target.lstrip("/")).exists()


def rule_links(project: Project) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    for rel in scanned_files(project.root):
        for number, line in scan_lines(project.root, rel):
            text = INLINE_CODE.sub("", line)
            targets = [m.group(1) for m in INLINE_LINK.finditer(text)]
            definition = REFERENCE_DEFINITION.fullmatch(text)
            if definition:
                targets.append(definition.group(1))
            for target in targets:
                if not link_exists(project.root, rel, target):
                    out.append(Diagnostic(rel, number, "link-broken", f"the link target {target} does not exist"))
    return out


def rule_secrets(project: Project) -> List[Diagnostic]:
    out: List[Diagnostic] = []
    for rel in scanned_files(project.root) + [PROJECT_FILE]:
        text = read_text(project.root / rel) or ""
        for number, line in enumerate(text.split("\n"), 1):
            for name, pattern in SECRET_PATTERNS:
                if pattern.search(line):
                    out.append(Diagnostic(
                        rel, number, "secret",
                        f"the line matches the {name} pattern; keep the secret out of the repository "
                        "and record where it lives in docs/inputs.md",
                    ))
    return out


RULES: Dict[str, Callable[[Project], List[Diagnostic]]] = {
    "docs": rule_docs,
    "index": rule_index,
    "register": rule_register,
    "prd": rule_prd,
    "refs": rule_refs,
    "coverage": rule_coverage,
    "backlog": rule_backlog,
    "sources": rule_sources,
    "links": rule_links,
    "secrets": rule_secrets,
}


def run_check(project: Project, groups: Sequence[str]) -> List[Diagnostic]:
    found = [d for d in project.parse_diagnostics if CODES[d.code] in groups]
    for group in groups:
        if group in RULES:
            found += RULES[group](project)
    return sorted(set(found), key=Diagnostic.sort_key)


def render_docs_index(project: Project) -> str:
    out = ["<!-- mirage:generated index -->", "", f"# {project.facets.name}", "", GENERATED_NOTE]
    out += ["", "## Reading order", ""]
    out += md_table(["Key", "Document", "Path", "Exists"], [
        [doc.key, doc.kind.title, f"`{doc.path}`",
         "yes" if doc.path == DOCS_INDEX or (project.root / doc.path).exists() else "no"]
        for doc in project.plan
    ])
    questions = project.unique_questions
    out += ["", "## Open questions", ""]
    out += md_table(["ID", "Question", "Blocks"], [
        [q.id, q.title, ", ".join(question_blocks(project, q)) or "-"] for q in questions if q.status == "open"
    ])
    out += ["", "## Delegated answers awaiting confirmation", ""]
    out += md_table(["ID", "Question", "Answer"], [
        [q.id, q.title, q.value("Answer") or "-"] for q in questions if q.status == "delegated"
    ])
    out += ["", "## Missing inputs", ""]
    out += md_table(["ID", "Input", "Needed for"], [
        [i.id, i.title, ", ".join(i.needed_for) or "-"] for i in project.unique_inputs if i.status == "missing"
    ])
    counts = [
        ("Requirements", len(project.requirement_ids)),
        ("Questions", len(project.question_by_id)),
        ("Inputs", len(project.input_by_id)),
        ("ADRs", len(adr_numbers(project.root))),
    ] + [(LEVEL_PLURALS[level], len(project.items_at(level))) for level in LEVELS]
    out += ["", "## Counts", ""]
    out += md_table(["Kind", "Count"], [[name, str(count)] for name, count in counts])
    return "\n".join(out) + "\n"


def index_blockers(project: Project, item: Item) -> List[str]:
    """The item's own blockers, then every question and input it still waits on."""
    ids = list(item.listed("blocked_by"))
    for unmet in unmet_prerequisites(project, item):
        if unmet.id.startswith(("Q-", "IN-")) and unmet.id not in ids:
            ids.append(unmet.id)
    return ids


def render_backlog_index(project: Project) -> str:
    out = ["<!-- mirage:generated backlog -->", "", "# Backlog", "", GENERATED_NOTE]
    work = project.items_at(*WORK_LEVELS)
    milestones = {m.id for m in project.items_at("milestone")} | {w.milestone for w in work}
    for milestone_id in sorted(milestones, key=natural_key):
        milestone = project.items.get(milestone_id)
        out += ["", f"## {milestone_id} {milestone.title}".rstrip() if milestone else f"## {milestone_id}", ""]
        if milestone is not None:
            out += [f"Status: {milestone.status or '-'}.", ""]
        rows = sorted((w for w in work if w.milestone == milestone_id), key=lambda w: natural_key(w.id))
        out += md_table(["ID", "Title", "Status", "Lane", "Blockers"], [
            [w.id, w.title, w.status or "-", w.lane or "-", ", ".join(index_blockers(project, w)) or "-"]
            for w in rows
        ])
    out += ["", "## Epics", ""]
    out += md_table(["ID", "Title", "Status"], [[e.id, e.title, e.status or "-"] for e in project.items_at("epic")])
    return "\n".join(out) + "\n"


GENERATED: Dict[str, Callable[[Project], str]] = {
    DOCS_INDEX: render_docs_index,
    BACKLOG_INDEX: render_backlog_index,
}


def ready_report(project: Project) -> List[dict]:
    lanes: Dict[Optional[str], dict] = {}
    for item in project.items_at(*WORK_LEVELS):
        unmet = unmet_prerequisites(project, item)
        entry = {"id": item.id, "title": item.title, "status": item.status}
        if item.status == "ready":
            bucket = "wrongly_ready" if unmet else "ready_now"
            if unmet:
                entry["unmet"] = [str(u) for u in unmet]
        elif (item.status in ("draft", "blocked") and not unmet and not item.scalar("blocked_reason")
              and not body_section_problems(item) and not lacks_requirement(item)):
            bucket = "can_become_ready"
        else:
            continue
        lane = lanes.setdefault(item.lane, {
            "lane": item.lane, "ready_now": [], "can_become_ready": [], "wrongly_ready": [],
        })
        lane[bucket].append(entry)
    return [lanes[key] for key in sorted(lanes, key=lambda lane: (lane is None, lane or ""))]


def render_ready(report: List[dict]) -> str:
    if not report:
        return "nothing is ready or can become ready"
    out: List[str] = []
    for lane in report:
        out.append(f"lane {lane['lane'] or '(none)'}")
        for bucket, label in (("ready_now", "ready now"), ("can_become_ready", "can become ready"),
                              ("wrongly_ready", "wrongly ready")):
            out.append(f"  {label}")
            for entry in lane[bucket]:
                text = f"    {entry['id']} {entry['title']}"
                if bucket == "can_become_ready":
                    text += f" ({entry['status']})"
                if "unmet" in entry:
                    text += ": " + ", ".join(entry["unmet"])
                out.append(text)
            if not lane[bucket]:
                out.append("    none")
    return "\n".join(out)


def format_scalar(text: str) -> str:
    if text and text == text.strip() and text[0] not in "\"[":
        return text
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def set_status(root: Path, ids: Sequence[str], status: str, evidence: Optional[str]) -> List[str]:
    """Change every named item, or none of them when any one is refused."""
    if status not in STATUSES:
        raise UsageError(f"unknown status {status!r}; use one of {', '.join(STATUSES)}")
    if evidence is not None and ("\n" in evidence or not evidence.strip()):
        raise UsageError("evidence must be one non-empty line")
    items, _ = load_backlog(root)
    edits = [status_edit(root, items, item_id, status, evidence) for item_id in dict.fromkeys(ids)]
    for path, text, _ in edits:
        atomic_write(path, text)
    return [line for _, _, line in edits]


def status_edit(root: Path, items: Dict[str, Item], item_id: str, status: str,
                evidence: Optional[str]) -> Tuple[Path, str, str]:
    """The file, its new text and the report line for one status change, without writing."""
    item = items.get(item_id)
    if item is None:
        raise UsageError(f"{item_id} has no file in {BACKLOG_DIR}/")
    path = root / item.path
    with open(path, encoding="utf-8", newline="") as stream:
        lines = re.split(r"(?<=\n)", stream.read())
    end = frontmatter_end([line.rstrip("\r\n") for line in lines])
    header = range(1, end - 1)
    status_at = next((i for i in header if lines[i].startswith("status:")), None)
    if status_at is None:
        raise UsageError(f"{item.path} has no status line in its frontmatter")
    evidence_at = next((i for i in header if lines[i].startswith("evidence:")), None)
    if status == "done" and evidence is None and not item.scalar("evidence"):
        raise UsageError(f"{item_id} has no evidence; pass --evidence to mark it done")
    newline = lines[status_at][len(lines[status_at].rstrip("\r\n")):] or "\n"
    lines[status_at] = f"status: {status}{newline}"
    if evidence is not None:
        evidence_line = f"evidence: {format_scalar(evidence)}{newline}"
        if evidence_at is None:
            lines.insert(end - 1, evidence_line)
        else:
            lines[evidence_at] = evidence_line
    return path, "".join(lines), f"{item_id}: {item.status or '-'} -> {status}"


def tracker_path(root: Path, tracker: str) -> Path:
    if not SLUG.fullmatch(tracker):
        raise UsageError(f"tracker name {tracker!r} must be a lowercase slug")
    return root / TRACKERS_DIR / f"{tracker}.json"


def load_tracker_map(root: Path, tracker: str) -> dict:
    """The whole map. Keys other than items and links belong to the adapter and pass through untouched."""
    path = tracker_path(root, tracker)
    if not path.exists():
        return {"tracker": tracker, "items": {}, "links": []}
    data = read_json(path, path.relative_to(root).as_posix())
    items = data.get("items", {}) if isinstance(data, dict) else None
    links = data.get("links", []) if isinstance(data, dict) else None
    if not isinstance(items, dict) or not all(isinstance(v, dict) for v in items.values()) or not (
        isinstance(links, list) and all(isinstance(l, list) and len(l) == 2 for l in links)
    ):
        raise UsageError(f"cannot read {path}: expected items as an object and links as [from, to] pairs")
    data["items"] = items
    data["links"] = [[str(a), str(b)] for a, b in links]
    return data


def write_tracker_map(root: Path, tracker: str, data: dict) -> None:
    out = dict(data)
    out["items"] = {key: data["items"][key] for key in sorted(data["items"], key=natural_key)}
    pairs = sorted({(a, b) for a, b in data["links"]}, key=lambda l: (natural_key(l[0]), natural_key(l[1])))
    out["links"] = [list(pair) for pair in pairs]
    atomic_write(tracker_path(root, tracker), json.dumps(out, indent=2, ensure_ascii=False) + "\n")


def sync_labels(items: Dict[str, Item], item: Item) -> List[str]:
    """The item's own labels, then the labels derived from its story: type, scope and release."""
    story: Optional[Item] = None
    derived: List[str] = []
    if item.level == "story":
        story = item
        derived.append(f"type:{item.kind}")
    elif item.level == "task":
        story = items.get(item.parent or "")
    if story is not None:
        derived += [f"{key}:{story.scalar(key)}" for key in ("scope", "release") if story.scalar(key)]
    labels = list(item.listed("labels"))
    return labels + [label for label in derived if label not in labels]


def sync_body(item: Item) -> str:
    kept = [line for line in item.body if not MIRAGE_COMMENT.fullmatch(line.strip())]
    body = "\n".join(kept).strip("\n")
    fields = (
        ("Requirements", list(item.listed("req"))), ("Questions", list(item.listed("questions"))),
        ("Inputs", list(item.listed("inputs"))), ("Blocked by", list(item.listed("blocked_by"))),
        ("Evidence", [item.scalar("evidence")] if item.scalar("evidence") else []),
    )
    footer = [f"{name}: {', '.join(values)}" for name, values in fields if values]
    return (body + "\n\n" if body else "") + "---\n" + "\n".join(footer + [f"mirage-id: {item.id}"])


def payload_hash(payload: dict) -> str:
    fields = {key: value for key, value in payload.items() if key not in ("hash", "remote_id")}
    text = json.dumps(fields, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def item_payload(items: Dict[str, Item], item: Item) -> dict:
    payload = {
        "id": item.id,
        "level": item.level,
        "title": f"{item.id} {item.title}",
        "status": item.status,
        "priority": item.scalar("priority") or None,
        "labels": sync_labels(items, item),
        "estimate": item.estimate,
        "due": item.scalar("due") or None,
        "milestone": item.milestone,
        "epic": item.epic,
        "parent": item.parent,
        "body": sync_body(item),
    }
    payload["hash"] = payload_hash(payload)
    return payload


def sync_plan(items: Dict[str, Item], tracker_map: dict) -> List[dict]:
    mapped = tracker_map["items"]
    ordered = sorted(items.values(), key=lambda i: (LEVEL_RANK[i.level], natural_key(i.id)))
    payloads = {i.id: item_payload(items, i) for i in ordered}
    ops: List[dict] = [{"op": "create", **payloads[i.id]} for i in ordered if i.id not in mapped]
    ops += [
        {"op": "update", **payloads[i.id], "remote_id": mapped[i.id].get("remote_id")}
        for i in ordered if i.id in mapped and mapped[i.id].get("hash") != payloads[i.id]["hash"]
    ]
    edges = sorted(
        {(i.id, b) for i in ordered if i.level in WORK_LEVELS for b in i.listed("blocked_by") if b in items},
        key=lambda e: (natural_key(e[0]), natural_key(e[1])),
    )
    recorded = {(a, b) for a, b in tracker_map["links"]}

    def link(op: str, a: str, b: str) -> dict:
        return {"op": op, "from": a, "to": b,
                "from_remote_id": mapped.get(a, {}).get("remote_id"),
                "to_remote_id": mapped.get(b, {}).get("remote_id")}

    ops += [link("link", a, b) for a, b in edges if a in mapped and b in mapped and (a, b) not in recorded]
    current = set(edges)
    ops += [link("unlink", a, b) for a, b in sorted(recorded - current, key=lambda e: (natural_key(e[0]), natural_key(e[1])))]
    ops += [
        {"op": "orphan", "id": key, "remote_id": mapped[key].get("remote_id")}
        for key in sorted(mapped, key=natural_key) if key not in items
    ]
    return ops


def sync_expect(items: Dict[str, Item], tracker_map: dict) -> List[dict]:
    """The payload each mapped item last pushed, for every item whose file still matches the map's hash."""
    mapped = tracker_map["items"]
    out: List[dict] = []
    for item_id in sorted(mapped, key=natural_key):
        item = items.get(item_id)
        if item is None:
            continue
        payload = item_payload(items, item)
        if mapped[item_id].get("hash") == payload["hash"]:
            out.append({"op": "expect", **payload, "remote_id": mapped[item_id].get("remote_id")})
    return out


def sync_record(root: Path, args: argparse.Namespace) -> str:
    data = load_tracker_map(root, args.tracker)
    if args.id is not None:
        if args.remote_id is None:
            raise UsageError("--id needs --remote-id")
        items, _ = load_backlog(root)
        item = items.get(args.id)
        if item is None:
            raise UsageError(f"{args.id} has no file in {BACKLOG_DIR}/")
        previous = data["items"].get(args.id, {})
        data["items"][args.id] = {
            "remote_id": args.remote_id,
            "key": args.key if args.key is not None else previous.get("key"),
            "url": args.url if args.url is not None else previous.get("url"),
            "hash": item_payload(items, item)["hash"],
            "status": item.status,
        }
        message = f"recorded {args.id} as {args.remote_id}"
    elif args.remote_id is not None or args.key is not None or args.url is not None:
        raise UsageError("--remote-id, --key and --url go with --id only")
    elif args.forget is not None:
        items, _ = load_backlog(root)
        if args.forget in items:
            raise UsageError(f"{args.forget} still has a backlog file; forget only orphaned items")
        data["items"].pop(args.forget, None)
        data["links"] = [pair for pair in data["links"] if args.forget not in pair]
        message = f"forgot {args.forget}"
    else:
        source, target = args.link or args.unlink
        pair = [source, target]
        if args.link:
            for end in pair:
                if end not in data["items"]:
                    raise UsageError(f"{end} is not in the map; record it with --id first")
            if pair not in data["links"]:
                data["links"].append(pair)
            message = f"linked {source} -> {target}"
        else:
            data["links"] = [l for l in data["links"] if l != pair]
            message = f"unlinked {source} -> {target}"
    write_tracker_map(root, args.tracker, data)
    return message


def plan_entries(project: Project) -> List[dict]:
    covered = {key for question in project.questions for key in question.covers}
    return [
        {
            "key": doc.key,
            "id": doc.kind.id,
            "title": doc.kind.title,
            "path": doc.path,
            "reason": doc.reason,
            "exists": (project.root / doc.path).exists(),
            "sections": [{"key": s.key, "title": s.title} for s in doc.kind.sections],
            "areas": [
                {"key": f"{doc.key}/{a.key}", "ask": a.ask, "covered": f"{doc.key}/{a.key}" in covered}
                for a in doc.kind.areas
            ],
            "inputs": [{"key": i.key, "title": i.title, "kind": i.kind} for i in doc.kind.inputs],
        }
        for doc in project.plan
    ]


def render_plan(entries: List[dict]) -> str:
    blocks = []
    for doc in entries:
        lines = [
            f"{doc['key']}: {doc['title']}",
            f"  path: {doc['path']} ({'exists' if doc['exists'] else 'missing'})",
            f"  reason: {doc['reason']}",
        ]
        lines += [f"  section {s['key']}: {s['title']}" for s in doc["sections"]]
        lines += [f"  area {a['key']}: {'covered' if a['covered'] else 'uncovered'}" for a in doc["areas"]]
        lines += [f"  input {i['key']}: {i['title']} ({i['kind']})" for i in doc["inputs"]]
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)


def emit_json(data: object) -> None:
    print(json.dumps(data, indent=2, ensure_ascii=False))


def cmd_check(root: Path, args: argparse.Namespace) -> int:
    groups = list(GROUPS)
    if args.only:
        groups = [g.strip() for g in args.only.split(",") if g.strip()]
        unknown = [g for g in groups if g not in GROUPS]
        if unknown or not groups:
            raise UsageError(f"unknown group {', '.join(unknown) or '(none)'}; groups: {', '.join(GROUPS)}")
    found = run_check(load_project(root), groups)
    if args.json:
        emit_json({"errors": [d.as_json() for d in found]})
    else:
        for diagnostic in found:
            print(diagnostic.render())
        print("ok" if not found else f"{len(found)} error{'s' if len(found) != 1 else ''}")
    return 1 if found else 0


def docs_ready_problems(project: Project) -> List[Diagnostic]:
    """What `check` would report that stops the backlog from being planned, plus an empty PRD."""
    found = run_check(project, DOCS_READY_GROUPS) + check_coverage_area(project)
    if all(req.scope == "OUT" for req in project.requirements):
        found.append(Diagnostic(PRD_FILE, None, "prd-empty", "no requirement is in scope"))
    audit_log = read_text(project.root / AUDIT_LOG)
    if audit_log is not None and not any(AUDIT_ENTRY.match(line) for line in audit_log.splitlines()):
        found.append(Diagnostic(AUDIT_LOG, None, "audit-missing", "no documents audit is recorded; run mirage-audit"))
    return sorted({d for d in found if not d.path.startswith(BACKLOG_DIR + "/")}, key=Diagnostic.sort_key)


def open_questions(project: Project) -> List[dict]:
    return [{"id": q.id, "title": q.title, "blocks": question_blocks(project, q)}
            for q in project.unique_questions if q.status == "open"]


def cmd_docs_ready(root: Path, args: argparse.Namespace) -> int:
    project = load_project(root)
    problems = docs_ready_problems(project)
    open_list = open_questions(project)
    if args.json:
        emit_json({"sufficient": not problems, "errors": [d.as_json() for d in problems], "open_questions": open_list})
    else:
        for diagnostic in problems:
            print(diagnostic.render())
        print("sufficient" if not problems else f"not sufficient: {len(problems)} problem{'s' if len(problems) != 1 else ''}")
        for question in open_list:
            print(f"open: {question['id']} {question['title']} (blocks: {', '.join(question['blocks']) or 'nothing'})")
    return 1 if problems else 0


def cmd_plan(root: Path, args: argparse.Namespace) -> int:
    entries = plan_entries(load_project(root))
    if args.json:
        emit_json({"docs": entries})
    else:
        print(render_plan(entries))
    return 0


def cmd_ready(root: Path, args: argparse.Namespace) -> int:
    report = ready_report(load_project(root))
    if args.json:
        emit_json({"lanes": report})
    else:
        print(render_ready(report))
    return 0


def cmd_index(root: Path, args: argparse.Namespace) -> int:
    project = load_project(root)
    for rel, render in GENERATED.items():
        text = render(project)
        if read_text(root / rel) == text:
            print(f"{rel} unchanged")
        else:
            atomic_write(root / rel, text)
            print(f"{rel} written")
    return 0


def cmd_set_status(root: Path, args: argparse.Namespace) -> int:
    print("\n".join(set_status(root, args.ids, args.status, args.evidence)))
    return 0


def cmd_sync_plan(root: Path, args: argparse.Namespace) -> int:
    tracker_map = load_tracker_map(root, args.tracker)
    items, _ = load_backlog(root)
    for op in sync_plan(items, tracker_map):
        print(json.dumps(op, ensure_ascii=False))
    return 0


def cmd_sync_expect(root: Path, args: argparse.Namespace) -> int:
    tracker_map = load_tracker_map(root, args.tracker)
    items, _ = load_backlog(root)
    for op in sync_expect(items, tracker_map):
        print(json.dumps(op, ensure_ascii=False))
    return 0


def cmd_sync_record(root: Path, args: argparse.Namespace) -> int:
    print(sync_record(root, args))
    return 0


def cmd_version(root: Path, args: argparse.Namespace) -> int:
    print(MIRAGE_VERSION)
    return 0


def resolve_root(given: Optional[str]) -> Path:
    if given:
        return Path(given)
    here = Path(__file__).resolve().parent
    return here.parent if here.name == ".mirage" else Path.cwd()


def build_parser() -> argparse.ArgumentParser:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--root", metavar="PATH", help="project root (default: the parent of .mirage/, else the current directory)")
    parser = argparse.ArgumentParser(prog="check.py", description="Validate and plan a mirage project.")
    commands = parser.add_subparsers(dest="command", required=True, metavar="COMMAND")

    def command(name: str, handler: Callable[[Path, argparse.Namespace], int], help_text: str) -> argparse.ArgumentParser:
        sub = commands.add_parser(name, parents=[common], help=help_text, description=help_text)
        sub.set_defaults(handler=handler)
        return sub

    check = command("check", cmd_check, "Run the rule groups and print every error.")
    check.add_argument("--only", metavar="GROUP[,GROUP]", help=f"groups to run: {', '.join(GROUPS)}")
    check.add_argument("--json", action="store_true")
    command("plan", cmd_plan, "Print the planned documents with their areas and inputs.").add_argument("--json", action="store_true")
    command("docs-ready", cmd_docs_ready, "Say whether the documentation is sufficient to plan the backlog.").add_argument("--json", action="store_true")
    command("ready", cmd_ready, "Print ready, can-become-ready and wrongly-ready items by lane.").add_argument("--json", action="store_true")
    command("index", cmd_index, "Write docs/README.md and backlog/README.md.")
    status = command("set-status", cmd_set_status, "Rewrite the status of one or more backlog items.")
    status.add_argument("ids", nargs="+", metavar="ID")
    status.add_argument("status")
    status.add_argument("--evidence", metavar="TEXT")
    command("sync-plan", cmd_sync_plan, "Print tracker operations as JSON lines.").add_argument("tracker")
    command("sync-expect", cmd_sync_expect, "Print what the tracker holds for each unchanged mapped item.").add_argument("tracker")
    record = command("sync-record", cmd_sync_record, "Record one tracker result in the map.")
    record.add_argument("tracker")
    action = record.add_mutually_exclusive_group(required=True)
    action.add_argument("--id")
    action.add_argument("--link", nargs=2, metavar=("FROM", "TO"))
    action.add_argument("--unlink", nargs=2, metavar=("FROM", "TO"))
    action.add_argument("--forget", metavar="ID", help="drop an orphaned item and its links from the map")
    record.add_argument("--remote-id", metavar="RID")
    record.add_argument("--key")
    record.add_argument("--url")
    command("version", cmd_version, "Print the mirage version.")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.handler(resolve_root(args.root), args)
    except UsageError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    sys.exit(main())
